const LSstate = [
  {
    id: "a86c1490eaf088",
    creator_id: "",
    name: "EagerBeaver",
    alias: "EagerBeaver",
    data: [
      {
        name: "Approval",
        type: "event",
        inputs: [
          { name: "owner", type: "address", meta: ["indexed"] },
          { name: "approved", type: "address", meta: ["indexed"] },
          { name: "tokenId", type: "uint256", meta: ["indexed"] },
        ],
        description: "",
        isHidden: false,
        isNative: false,
      },
      {
        name: "ApprovalForAll",
        type: "event",
        inputs: [
          { name: "owner", type: "address", meta: ["indexed"] },
          { name: "operator", type: "address", meta: ["indexed"] },
          { name: "approved", type: "bool", meta: [] },
        ],
        description: "",
        isHidden: false,
        isNative: false,
      },
      {
        name: "OwnershipTransferred",
        type: "event",
        inputs: [
          { name: "previousOwner", type: "address", meta: ["indexed"] },
          { name: "newOwner", type: "address", meta: ["indexed"] },
        ],
        description: "",
        isHidden: false,
        isNative: false,
      },
      {
        name: "Transfer",
        type: "event",
        inputs: [
          { name: "from", type: "address", meta: ["indexed"] },
          { name: "to", type: "address", meta: ["indexed"] },
          { name: "tokenId", type: "uint256", meta: ["indexed"] },
        ],
        description: "",
        isHidden: false,
        isNative: false,
      },
      {
        name: "_merkleRoot",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "bytes32" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "_paused",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "bool" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "_price",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "_revealed",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "bool" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "approve",
        type: "function",
        inputs: [
          { name: "to", type: "address", meta: [] },
          { name: "tokenId", type: "uint256", meta: [] },
        ],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "balanceOf",
        type: "function",
        inputs: [{ name: "owner", type: "address", meta: [] }],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "currentId",
        type: "function",
        inputs: [],
        outputs: [{ name: "_value", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "getApproved",
        type: "function",
        inputs: [{ name: "tokenId", type: "uint256", meta: [] }],
        outputs: [{ name: "", type: "address" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "isApprovedForAll",
        type: "function",
        inputs: [
          { name: "owner", type: "address", meta: [] },
          { name: "operator", type: "address", meta: [] },
        ],
        outputs: [{ name: "", type: "bool" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "maxTokenIds",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "mint",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["payable"],
      },
      {
        name: "name",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "string" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "owner",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "address" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "ownerOf",
        type: "function",
        inputs: [{ name: "tokenId", type: "uint256", meta: [] }],
        outputs: [{ name: "", type: "address" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "presaleMint",
        type: "function",
        inputs: [{ name: "_merkleProof", type: "bytes32[]", meta: [] }],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["payable"],
      },
      {
        name: "renounceOwnership",
        type: "function",
        inputs: [],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "revealCollection",
        type: "function",
        inputs: [{ name: "revealedBaseURI", type: "string", meta: [] }],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["nonpayable"],
      },
      {
        name: "safeTransferFrom",
        type: "function",
        inputs: [
          { name: "from", type: "address", meta: [] },
          { name: "to", type: "address", meta: [] },
          { name: "tokenId", type: "uint256", meta: [] },
        ],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "safeTransferFrom",
        type: "function",
        inputs: [
          { name: "from", type: "address", meta: [] },
          { name: "to", type: "address", meta: [] },
          { name: "tokenId", type: "uint256", meta: [] },
          { name: "_data", type: "bytes", meta: [] },
        ],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "setApprovalForAll",
        type: "function",
        inputs: [
          { name: "operator", type: "address", meta: [] },
          { name: "approved", type: "bool", meta: [] },
        ],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "setPaused",
        type: "function",
        inputs: [{ name: "val", type: "bool", meta: [] }],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["nonpayable"],
      },
      {
        name: "supportsInterface",
        type: "function",
        inputs: [{ name: "interfaceId", type: "bytes4", meta: [] }],
        outputs: [{ name: "", type: "bool" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "symbol",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "string" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "timeToEndPresale",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "timeToStartPresale",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "tokenByIndex",
        type: "function",
        inputs: [{ name: "index", type: "uint256", meta: [] }],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "tokenCount",
        type: "function",
        inputs: [],
        outputs: [{ name: "_value", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "tokenOfOwnerByIndex",
        type: "function",
        inputs: [
          { name: "owner", type: "address", meta: [] },
          { name: "index", type: "uint256", meta: [] },
        ],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "tokenURI",
        type: "function",
        inputs: [{ name: "tokenId", type: "uint256", meta: [] }],
        outputs: [{ name: "", type: "string" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "totalSupply",
        type: "function",
        inputs: [],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view"],
      },
      {
        name: "transferFrom",
        type: "function",
        inputs: [
          { name: "from", type: "address", meta: [] },
          { name: "to", type: "address", meta: [] },
          { name: "tokenId", type: "uint256", meta: [] },
        ],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "transferOwnership",
        type: "function",
        inputs: [{ name: "newOwner", type: "address", meta: [] }],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "withdraw",
        type: "function",
        inputs: [],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["nonpayable"],
      },
    ],
    showInherited: { function: false, event: false },
  },
];
export const sampleContractData = [
  {
    id: "371b97e16240e6",
    creator_id: "",
    name: "eagerBeaverNFT",
    alias: "eagerBeaverNFT",
    data: [
      {
        name: "mintNFT",
        type: "function",
        inputs: [
          { name: "amount", type: "uint256" },
          { name: "name", type: "string" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view", "payable"],
      },
      {
        name: "Mint",
        type: "event",
        inputs: [{ name: "", type: "", meta: [] }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["anonymous"],
      },
      {
        name: "approve",
        type: "function",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "tokenId",
            type: "uint256",
          },
        ],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "balanceOf",
        type: "function",
        inputs: [{ name: "owner", type: "address" }],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "getApproved",
        type: "function",
        inputs: [{ name: "tokenId", type: "uint256" }],
        outputs: [{ name: "", type: "address" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "Approval",
        type: "event",
        inputs: [
          {
            meta: ["indexed"],
            name: "owner",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "approved",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "tokenId",
            type: "uint256",
          },
        ],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["anonymous"],
      },
    ],
  },
  {
    id: "5761bsgqs561a",
    creator_id: "",
    name: "auctionGuruNFT",
    alias: "auctionGuruNFT",
    data: [
      {
        name: "mintNFT",
        type: "function",
        inputs: [
          { name: "amount", type: "uint256" },
          { name: "name", type: "string" },
        ],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["view", "payable"],
      },
      {
        name: "revealCollection",
        type: "function",
        inputs: [{ name: "revealedBaseURI", type: "string" }],
        outputs: [{ name: "tokenId", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["nonpayable"],
      },
      {
        name: "presaleMint",
        type: "function",
        inputs: [{ name: "_merkleProof", type: "bytes32[]" }],
        outputs: [{ name: "tokenId", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["payable"],
      },
      {
        inputs: [],
        name: "renounceOwnership",
        outputs: [],
        type: "function",
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["nonpayable"],
      },
      {
        inputs: [
          {
            meta: ["indexed"],
            name: "from",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "to",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "tokenId",
            type: "uint256",
          },
        ],
        name: "Transfer",
        type: "event",
        meta: ["anonymous"],
        description: "",
        isHidden: false,
        isNative: true,
      },
      {
        name: "Mint",
        type: "event",
        inputs: [{ name: "", type: "", meta: [] }],
        description: "",
        isHidden: false,
        isNative: true,
        meta: ["anonymous"],
      },
      {
        name: "approve",
        type: "function",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "tokenId",
            type: "uint256",
          },
        ],
        outputs: [],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["nonpayable"],
      },
      {
        name: "balanceOf",
        type: "function",
        inputs: [{ name: "owner", type: "address" }],
        outputs: [{ name: "", type: "uint256" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "getApproved",
        type: "function",
        inputs: [{ name: "tokenId", type: "uint256" }],
        outputs: [{ name: "", type: "address" }],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["view"],
      },
      {
        name: "Approval",
        type: "event",
        inputs: [
          {
            meta: ["indexed"],
            name: "owner",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "approved",
            type: "address",
          },
          {
            meta: ["indexed"],
            name: "tokenId",
            type: "uint256",
          },
        ],
        description: "",
        isHidden: false,
        isNative: false,
        meta: ["anonymous"],
      },
    ],
  },
];
